### PR TITLE
Tutoring Merge

### PR DESCRIPTION
**Pull request by sidijju**
Added files used to complete tutoring merge between rails and dev. JSON files used as reference for Python program.

### CODE REVIEW

**Comment by ochan1** [comment]
Let's change the "dict" variable names to something more meaningful and doesn't conflict with the original Python "dict"

**Comment by sidijju** [comment]
Added mroe meaningful variable names

**Comment by ochan1** [comment]
Design Document for Code: https://www.notion.so/hkn/Tutoring-Scheduler-Data-Merging-51cb8e117060443e9aaccaac525699bc

**Comment by ochan1** [comment]
LGTM

**Pull request merged**
